# Generated by Django 5.1 on 2024-09-02 12:08

import common_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', common_utils.fields.PhoneNumberField(max_length=15, validators=[common_utils.fields.validate_phone_number])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interested_products', models.ManyToManyField(related_name='leads', related_query_name='lead', to='products.product')),
            ],
        ),
    ]
